In [5]:
import os
os.getcwd

In [16]:
import pandas as pd

df = pd.read_csv(r"D:\NHS-ML-Project\hospital-readmission-ml-and-nhs-ae-dashboard\data\nhs.csv", skiprows=14)
df.head()

,Unnamed: 0,Unnamed: 1,A&E attendances,Unnamed: 3,Unnamed: 4,Unnamed: 5,"A&E attendances < 4 hours from arrival to admission, transfer or discharge",Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28
0,Code,System,Type 1 Departments - Major A&E,Type 2 Departments - Single Specialty,Type 3 Departments - Other A&E/Minor Injury Unit,Total attendances,Type 1 Departments - Major A&E,Type 2 Departments - Single Specialty,Type 3 Departments - Other A&E/Minor Injury Unit,Total Attendances < 4 hours,...,Emergency Admissions via Type 2 A&E,Emergency Admissions via Type 3 and 4 A&E,Total Emergency Admissions via A&E,Other Emergency admissions (i.e not via A&E),Total Emergency Admissions,Number of patients spending >4 hours from deci...,Number of patients spending >12 hours from dec...,NaN,NaN,NaN
1,-,-,"1,478,144","55,393","898,735","2,432,272","947,365","53,329","874,867","1,875,561",...,"1,423","6,226","410,005","143,887","553,892","123,870","46,665",NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,QOX,"NHS Bath And North East Somerset, Swindon And ...","20,771",377,"12,448","33,596","11,678",377,"11,857","23,912",...,0,11,"7,293","4,480","11,773","2,567",668,NaN,NaN,NaN
4,QHG,"NHS Bedfordshire, Luton And Milton Keynes Inte...","26,816",0,"18,199","45,015","18,375",0,"18,106","36,481",...,0,0,"7,954","2,938","10,892",698,15,NaN,NaN,NaN

In [23]:
#check structure of the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 377 entries, 0 to 376
Data columns (total 29 columns):
 #   Column                                                                      Non-Null Count  Dtype
---  ------                                                                      --------------  -----
 0   Unnamed: 0                                                                  44 non-null     object
 1   Unnamed: 1                                                                  44 non-null     object
 2   A&E attendances                                                             44 non-null     object
 3   Unnamed: 3                                                                  44 non-null     object
 4   Unnamed: 4                                                                  44 non-null     object
 5   Unnamed: 5                                                                  44 non-null     object
 6   A&E attendances < 4 hours from arrival to admission, transfer or discharge  44 non-null     object
 7   Unnamed: 7                                                                  44 non-null     object
 8   Unnamed: 8                                                                  44 non-null     object
 9   Unnamed: 9                                                                  44 non-null     object
 10  A&E attendances > 4 hours from arrival to admission, transfer or discharge  44 non-null     object
 11  Unnamed: 11                                                                 44 non-null     object
 12  Unnamed: 12                                                                 44 non-null     object
 13  Unnamed: 13                                                                 44 non-null     object
 14  Percentage of attendances within 4 hours                                    44 non-null     object
 15  Unnamed: 15                                                                 44 non-null     object
 16  Unnamed: 16                                                                 44 non-null     object
 17  Unnamed: 17                                                                 44 non-null     object
 18  Emergency Admissions                                                        44 non-null     object
 19  Unnamed: 19                                                                 44 non-null     object
 20  Unnamed: 20                                                                 44 non-null     object
 21  Unnamed: 21                                                                 44 non-null     object
 22  Unnamed: 22                                                                 44 non-null     object
 23  Unnamed: 23                                                                 44 non-null     object
 24  Unnamed: 24                                                                 44 non-null     object
 25  Unnamed: 25                                                                 44 non-null     object
 26  Unnamed: 26                                                                 0 non-null      float64
 27  Unnamed: 27                                                                 0 non-null      float64
 28  Unnamed: 28                                                                 0 non-null      float64
dtypes: float64(3), object(26)
memory usage: 85.5+ KB

In [29]:
#check missing values
df.isnull().sum()

Unnamed: 0                                                                    333
Unnamed: 1                                                                    333
A&E attendances                                                               333
Unnamed: 3                                                                    333
Unnamed: 4                                                                    333
Unnamed: 5                                                                    333
A&E attendances < 4 hours from arrival to admission, transfer or discharge    333
Unnamed: 7                                                                    333
Unnamed: 8                                                                    333
Unnamed: 9                                                                    333
A&E attendances > 4 hours from arrival to admission, transfer or discharge    333
Unnamed: 11                                                                   333
Unnamed: 12                                                                   333
Unnamed: 13                                                                   333
Percentage of attendances within 4 hours                                      333
Unnamed: 15                                                                   333
Unnamed: 16                                                                   333
Unnamed: 17                                                                   333
Emergency Admissions                                                          333
Unnamed: 19                                                                   333
Unnamed: 20                                                                   333
Unnamed: 21                                                                   333
Unnamed: 22                                                                   333
Unnamed: 23                                                                   333
Unnamed: 24                                                                   333
Unnamed: 25                                                                   333
Unnamed: 26                                                                   377
Unnamed: 27                                                                   377
Unnamed: 28                                                                   377
dtype: int64

In [30]:
#view basic statistics of the data
df.describe()

       Unnamed: 26  Unnamed: 27  Unnamed: 28
count          0.0          0.0          0.0
mean           NaN          NaN          NaN
std            NaN          NaN          NaN
min            NaN          NaN          NaN
25%            NaN          NaN          NaN
50%            NaN          NaN          NaN
75%            NaN          NaN          NaN
max            NaN          NaN          NaN

In [31]:
df.tail()

,Unnamed: 0,Unnamed: 1,A&E attendances,Unnamed: 3,Unnamed: 4,Unnamed: 5,"A&E attendances < 4 hours from arrival to admission, transfer or discharge",Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28
372,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
373,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
374,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
375,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
376,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
df.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'A&E attendances', 'Unnamed: 3',
       'Unnamed: 4', 'Unnamed: 5',
       'A&E attendances < 4 hours from arrival to admission, transfer or discharge',
       'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'A&E attendances > 4 hours from arrival to admission, transfer or discharge',
       'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Percentage of attendances within 4 hours', 'Unnamed: 15',
       'Unnamed: 16', 'Unnamed: 17', 'Emergency Admissions', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27',
       'Unnamed: 28'],
      dtype='object')

In [33]:
df.head(10)

,Unnamed: 0,Unnamed: 1,A&E attendances,Unnamed: 3,Unnamed: 4,Unnamed: 5,"A&E attendances < 4 hours from arrival to admission, transfer or discharge",Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28
0,Code,System,Type 1 Departments - Major A&E,Type 2 Departments - Single Specialty,Type 3 Departments - Other A&E/Minor Injury Unit,Total attendances,Type 1 Departments - Major A&E,Type 2 Departments - Single Specialty,Type 3 Departments - Other A&E/Minor Injury Unit,Total Attendances < 4 hours,...,Emergency Admissions via Type 2 A&E,Emergency Admissions via Type 3 and 4 A&E,Total Emergency Admissions via A&E,Other Emergency admissions (i.e not via A&E),Total Emergency Admissions,Number of patients spending >4 hours from deci...,Number of patients spending >12 hours from dec...,NaN,NaN,NaN
1,-,-,"1,478,144","55,393","898,735","2,432,272","947,365","53,329","874,867","1,875,561",...,"1,423","6,226","410,005","143,887","553,892","123,870","46,665",NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,QOX,"NHS Bath And North East Somerset, Swindon And ...","20,771",377,"12,448","33,596","11,678",377,"11,857","23,912",...,0,11,"7,293","4,480","11,773","2,567",668,NaN,NaN,NaN
4,QHG,"NHS Bedfordshire, Luton And Milton Keynes Inte...","26,816",0,"18,199","45,015","18,375",0,"18,106","36,481",...,0,0,"7,954","2,938","10,892",698,15,NaN,NaN,NaN
5,QHL,NHS Birmingham And Solihull Integrated Care Board,"39,752",423,"14,808","54,983","24,886",423,"14,782","40,091",...,0,0,"11,406","7,843","19,249","4,425","1,513",NaN,NaN,NaN
6,QUY,"NHS Bristol, North Somerset And South Gloucest...","26,384","2,625","9,347","38,356","16,658","2,379","9,027","28,064",...,11,0,"8,238","4,078","12,316","2,666","1,105",NaN,NaN,NaN
7,QU9,"NHS Buckinghamshire, Oxfordshire And Berkshire...","36,610","5,549","15,460","57,619","25,561","5,518","15,178","46,257",...,974,58,"12,283","5,986","18,269","1,274",282,NaN,NaN,NaN
8,QUE,NHS Cambridgeshire And Peterborough Integrated...,"28,164",0,"11,428","39,592","17,338",0,"11,114","28,452",...,0,79,"7,242","1,879","9,121","2,310","1,349",NaN,NaN,NaN
9,QYG,NHS Cheshire And Merseyside Integrated Care Board,"74,941","3,578","51,120","129,639","42,894","3,377","49,386","95,657",...,122,0,"24,077","8,121","32,198","8,326","5,004",NaN,NaN,NaN